### ISSUE TITLE
Add loopprojectfile to pypi

### ISSUE THREAD

**Issue by lachlangrose** [Loop3D/LoopProjectFile#23]
Add python sdist build/wheel build for loopprojectfile and add action to push to pypi. I have allowed the action publish_conda.yml to push releases to pypi loopprojectfile. 

https://github.com/Loop3D/loopstructural-visualisation/edit/main/.github/workflows/release.yml should be a template for how to do this.

**Comment by rabii-chaarani** [comment]
Done
